{
  InvokerInvocationException failure=new InvokerInvocationException(new Throwable()){
    @Override public Throwable getCause(){
      return null;
    }
  }
;
  getTask().doFirst(createExceptionAction(failure));
  checkException(failure);
}
