{
  final TestException testException=context.mock(TestException.class);
  context.checking(new Expectations(){
{
      allowing(testException).getLocation();
      will(returnValue(location));
      allowing(testException).getOriginalMessage();
      will(returnValue(message));
      allowing(testException).getReportableCauses();
      will(returnValue(Arrays.asList(causes)));
    }
  }
);
  return testException;
}
