{
  try {
    task.execute();
    fail();
  }
 catch (  GradleException e) {
    assertThat(e.getCause(),instanceOf(InvalidUserDataException.class));
    assertThat(e.getCause().getMessage(),equalTo(expectedErrorMessage));
  }
}
