{
  Throwable failure=new GradleException();
  BuildResult result=new BuildResult(null,failure);
  try {
    result.rethrowFailure();
    fail();
  }
 catch (  Exception e) {
    assertThat(e,sameInstance(failure));
  }
}
