{
  try {
    execute.execute();
  }
 catch (  Exception e) {
    if (!(cause.equals(e.getCause().getClass()))) {
      Assert.fail();
    }
    return;
  }
  Assert.fail();
}
