{
  Throwable failure=locationAwareException(null);
  DefaultExceptionAnalyser analyser=analyser();
  notifyAnalyser(analyser,source);
  assertThat(analyser.transform(failure),sameInstance(failure));
}
