{
  try {
    invocation.proceed();
  }
 catch (  Throwable t) {
    if (!annotation.type().isInstance(t)) {
      throw new WrongExceptionThrownError(annotation.type(),t);
    }
    if (!annotation.message().equals(t.getMessage())) {
      throw new ComparisonFailure("Unexpected message for exception.",annotation.message(),t.getMessage());
    }
    return;
  }
  throw new WrongExceptionThrownError(annotation.type(),null);
}
