{
  final RuntimeException failure=new RuntimeException();
  context.checking(new Expectations(){
{
      one(action).execute(with(notNullValue(WorkerProcessContext.class)));
      will(throwException(failure));
      one(client).stop();
    }
  }
);
  try {
    main.execute(workerActionContext);
    fail();
  }
 catch (  RuntimeException e) {
    assertThat(e,sameInstance(failure));
  }
}
