{
  Throwable cause=locationAwareException(null);
  Throwable failure=locationAwareException(new RuntimeException(cause));
  DefaultExceptionAnalyser analyser=analyser();
  assertThat(analyser.transform(failure),sameInstance(cause));
}
