{
  configureTask();
  expectTestsFail();
  try {
    test.executeTests();
    fail();
  }
 catch (  GradleException e) {
    assertThat(e.getMessage(),startsWith("There were failing tests. See the report at"));
  }
}
