{
  final Throwable failure=context.mock(TestException.class);
  context.checking(new Expectations(){
{
      allowing(failure).getCause();
      will(returnValue(cause));
      allowing(failure).getStackTrace();
      will(returnValue(toArray(element)));
    }
  }
);
  return failure;
}
